parameters:
    payum.template.layout: 'SolidInvoicePaymentBundle::layout.html.twig'

payum:
    security:
        token_storage:
            SolidInvoice\PaymentBundle\Entity\SecurityToken:
                doctrine: orm
    storages:
        SolidInvoice\PaymentBundle\Entity\Payment:
            doctrine: orm
    dynamic_gateways:
        sonata_admin: false
        config_storage:
            SolidInvoice\PaymentBundle\Entity\PaymentMethod:
                doctrine: orm

payment:
    gateways:
        credit:
            factory: offline
        cash:
            factory: offline
        bank_transfer:
            factory: offline
        paypal_express_checkout:
            factory: paypal_express_checkout
            form: SolidInvoice\PaymentBundle\Form\Methods\PaypalExpressCheckout
        paypal_pro_checkout:
            factory: paypal_pro_checkout
            form: SolidInvoice\PaymentBundle\Form\Methods\PaypalProCheckout
        stripe_checkout:
            factory: stripe_checkout
            form: SolidInvoice\PaymentBundle\Form\Methods\StripeCheckout
        stripe_js:
            factory: stripe_js
            form: SolidInvoice\PaymentBundle\Form\Methods\StripeJs
        klarna_invoice:
            factory: klarna_invoice
            form: SolidInvoice\PaymentBundle\Form\Methods\KlarnaInvoice
        klarna_checkout:
            factory: klarna_checkout
            form: SolidInvoice\PaymentBundle\Form\Methods\KlarnaCheckout
        be2bill_offsite:
            factory: be2bill_offsite
            form: SolidInvoice\PaymentBundle\Form\Methods\Be2billOffsite
        be2bill_direct:
            factory: be2bill_direct
            form: SolidInvoice\PaymentBundle\Form\Methods\Be2billDirect
        authorize_net_aim:
            factory: authorize_net_aim
            form: SolidInvoice\PaymentBundle\Form\Methods\AuthorizeNetAim
        payex:
            factory: payex
            form: SolidInvoice\PaymentBundle\Form\Methods\Payex

              #authorizenet_sim:
              #    factory: omnipay_direct
              #    type: AuthorizeNet_SIM
              #    options: null
              #    payum.api: '@solidinvoice.payment.payum.authorize_net_sim_api'


              #buckaroo_ideal:
              #omnipay_direct:
              #type: Buckaroo_Ideal
              #options:

              #cardsave:
              #omnipay_direct:
              #type: CardSave
              #options:

              #coinbase:
              #omnipay_direct:
              #type: Coinbase
              #options:

              #eway_rapid:
              #omnipay_direct:
              #type: Eway_Rapid
              #options:

              #firstdata_connect:
              #omnipay_direct:
              #type: FirstData_Connect
              #options:

              #gocardless:
              #omnipay_direct:
              #type: GoCardless
              #options:

              #migs_threeparty:
              #omnipay_direct:
              #type: Migs_ThreeParty
              #options:

              #migs_twoparty:
              #omnipay_direct:
              #type: Migs_TwoParty
              #options:

              #mollie:
              #omnipay_direct:
              #type: Mollie
              #options:

              #multisafepay:
              #omnipay_direct:
              #type: MultiSafepay
              #options:

              #netaxept:
              #omnipay_direct:
              #type: Netaxept
              #options:

              #netbanx:
              #omnipay_direct:
              #type: NetBanx
              #options:

              #payfast:
              #omnipay_direct:
              #type: PayFast
              #options:

              #payflow_pro:
              #omnipay_direct:
              #type: Payflow_Pro
              #options:

              #paymentexpress_pxpay:
              #omnipay_direct:
              #type: PaymentExpress_PxPay
              #options:

              #paymentexpress_pxpost:
              #omnipay_direct:
              #type: PaymentExpress_PxPost
              #options:

              #pin:
              #omnipay_direct:
              #type: Pin
              #options:

              #sagepay_direct:
              #omnipay_direct:
              #type: SagePay_Direct
              #options:

              #sagepay_server:
              #omnipay_direct:
              #type: SagePay_Server
              #options:

              #securepay_directpost:
              #omnipay_direct:
              #type: SecurePay_DirectPost
              #options:

              #targetpay_directebanking:
              #omnipay_direct:
              #type: TargetPay_Directebanking
              #options:

              #targetpay_ideal:
              #omnipay_direct:
              #type: TargetPay_Ideal
              #options:

              #targetpay_mrcash:
              #omnipay_direct:
              #type: TargetPay_Mrcash
              #options:

              #twocheckout:
              #omnipay_direct:
              #type: TwoCheckout
              #options:

              #worldpay:
              #omnipay_direct:
              #type: WorldPay
            #options:
