services:
    _defaults:
        public: false
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Gedmo\Timestampable\TimestampableListener:
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]

    gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        public: true
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]
