services:
    _defaults:
        public: false
        autowire: true
        tags:
            - { name: form.type }

    SolidInvoice\InvoiceBundle\Form\Type\InvoiceType: ~
    SolidInvoice\InvoiceBundle\Form\Type\RecurringInvoiceType: ~
    SolidInvoice\InvoiceBundle\Form\Type\ItemType: ~
