services:
    _defaults:
        public: false
        tags:
            - { name: twig.extension }

    solidinvoice_menu.twig.extension:
        class: SolidInvoice\MenuBundle\Twig\Extension\MenuExtension
        calls:
            - [ setRenderer, [ '@solidinvoice_menu.renderer' ] ]
            - [ setProvider, [ '@solidinvoice_menu.provider' ] ]