services:
    _defaults:
        public: false
        tags:
            - { name: kernel.event_subscriber }

    SolidInvoice\PaymentBundle\Listener\:
        resource: '../../../Listener'
        autowire: true

    SolidInvoice\PaymentBundle\Listener\PaymentCompleteListener:
        autowire: true
        arguments:
            $stateMachine: '@state_machine.invoice'