solidinvoice_dashboard:
    resource: '@SolidInvoiceDashboardBundle/Resources/config/routing.yml'

solidinvoice_settings:
    resource: '@SolidInvoiceSettingsBundle/Resources/config/routing.yml'
    prefix: /

solidinvoice_core:
    resource: '@SolidInvoiceCoreBundle/Resources/config/routing.yml'
    prefix: /

solidinvoice_install:
    resource: '@SolidInvoiceInstallBundle/Resources/config/routing.yml'
    prefix: /

solidinvoice_client:
    prefix: /clients
    resource: '@SolidInvoiceClientBundle/Resources/config/routing.yml'

solidinvoice_quote:
    prefix: /quotes
    resource: '@SolidInvoiceQuoteBundle/Resources/config/routing.yml'

solidinvoice_invoice:
    prefix: /invoices
    resource: '@SolidInvoiceInvoiceBundle/Resources/config/routing.yml'

solidinvoice_payment:
    resource: '@SolidInvoicePaymentBundle/Resources/config/routing.yml'
    prefix: /payments

solidinvoice_tax:
    resource: '@SolidInvoiceTaxBundle/Resources/config/routing.yml'
    prefix: /tax

solidinvoice_user:
    resource: '@SolidInvoiceUserBundle/Resources/config/routing.yml'
    prefix: /

solidinvoice_datagrid:
    resource: '@SolidInvoiceDataGridBundle/Resources/config/routing.yml'
    prefix: /grid
