parameters:
    env(database_driver): 'pdo_mysql'
    env(database_host): '127.0.0.1'
    env(database_port): '3306'
    env(database_name): 'solidinvoice'
    env(database_user): 'root'
    env(database_password): ~
    env(database_version): '1.0'

    env(mailer_transport): 'gmail'
    env(mailer_host): 'smtp.gmail.com'
    env(mailer_user): 'aparejo0984@gmail.com'
    env(mailer_password): 'polomolok0984'
    env(mailer_port): '465'
    env(mailer_encryption): 'ssl'

    env(locale): 'en_US'
    env(secret): 'SecretToken'

    env(installed): ~
