_quotes_index:
    path: /
    defaults: { _controller: 'SolidInvoice\QuoteBundle\Action\Index' }

_quotes_create:
    path: '/create/{client}'
    defaults: { _controller: 'SolidInvoice\QuoteBundle\Action\Create', client: null }
    options:
        expose: true

_quotes_get_fields:
    path: '/fields/get/{currency}'
    defaults: { _controller: 'SolidInvoice\QuoteBundle\Action\Fields' }
    options:
        expose: true

_quotes_edit:
    path: '/edit/{id}'
    defaults: { _controller: 'SolidInvoice\QuoteBundle\Action\Edit' }
    options:
        expose: true

_quotes_view:
    path: '/view/{id}.{_format}'
    defaults: { _controller: 'SolidInvoice\QuoteBundle\Action\View', _format: html }
    requirements:
        _format: html|pdf
    options:
        expose: true

_quotes_clone:
    path: '/clone/{id}'
    defaults: { _controller: 'SolidInvoice\QuoteBundle\Action\CloneQuote' }

_send_quote:
    path: '/action/send/{id}'
    defaults:  { _controller: 'SolidInvoice\QuoteBundle\Action\Transition\Send' }

_transition_quote:
    path: '/action/{action}/{id}'
    defaults: { _controller: 'SolidInvoice\QuoteBundle\Action\Transition' }

_quotes_grid:
    resource: '@SolidInvoiceQuoteBundle/Action/Grid'
    type: grid