_tax_rates:
    path: /rates
    defaults: { _controller: 'SolidInvoice\TaxBundle\Action\Index' }

_tax_rates_add:
    path: /rates/add
    defaults: { _controller: 'SolidInvoice\TaxBundle\Action\Add' }

_tax_rates_edit:
    path: '/rates/edit/{id}'
    defaults: { _controller: 'SolidInvoice\TaxBundle\Action\Edit' }
    options:
        expose: true

_tax_rates_grid:
    resource: '@SolidInvoiceTaxBundle/Action/Grid'
    type: grid

_tax_number_validate:
    path: '/number/validate'
    defaults: { _controller: 'SolidInvoice\TaxBundle\Action\Validate' }
    methods: ['POST']
    options:
        expose: true

